name: firebase_with_getx_todo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.4
  firebase_core: ^2.18.0
  cloud_firestore: ^4.10.0
  get: 4.6.6
  flutter: 
    sdk: flutter
  lottie: ^2.6.0
  firebase_messaging: ^14.7.0
  grouped_list: ^5.1.2
  firebase_auth: ^4.11.1
  flutter_slidable: ^3.0.0
  google_fonts: ^4.0.4

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

fonts:
  - family: Pacifico
    fonts:
      - asset: fonts/Pacifico-Regular.ttf
      - asset: fonts/Belanosima-Bold.ttf
      - asset: fonts/PermanentMarker-Regular.ttf  

